### ISSUE TITLE
Security mapping

### ISSUE THREAD

**Issue by sashkoif** [Mangosoft-team/Demo#35]
I get this
```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "type" 
(class de.varengold.cdl.core.model.security.Security), not marked as ignorable (6 known
 properties: "currencyIso", "emittendId", "exchangeTradedYN", "symbol2", "name", "isin"])
 at [Source: (String)"{"isin":"XS0802005289","name":"Republic of Bulgaria 4,25 
07/09/17","emittendId":9494,"currencyIso":"EUR","exchangeTradedYN":"Y","symbol2":null,"type":2
,"emission":"2012-07-09","redemption":"2017-07-09"
,"interest":9,"nachrangYN":"N","coverage":0,"guaranteed":0,"perpetualYN":"N"}"; line: 1, column:
 152] (through reference chain: de.varengold.cdl.core.model.security.Security["type"])


```

**Comment by CT-VG** [comment]
When do you get this message?
Which endpoint did you call with what parameters/body?

**Comment by sashkoif** [comment]
GET "securities/"+isin
I need Security for SecurityColleteral on SecurityAgreement slide

**Comment by CT-VG** [comment]
should be fixed

**Comment by sashkoif** [comment]
Did you add something that I should pay attention to? Because I get the same

**Comment by CT-VG** [comment]
Okay. This should be resolved. Please tell me which ISIN you are requesting.

**Comment by sashkoif** [comment]
"securityIsin": "XS0802005289"

**Comment by CT-VG** [comment]
I can only reproduce the error in your project. 
When doing a standalone test with the given backend I don't get the error.
Please double check that you have the latest versions from GIT

**Comment by sashkoif** [comment]
I added the last core model
![img2](https://user-images.githubusercontent.com/14570032/59819258-b9b67800-932f-11e9-9110-d04248deb280.png)
After that I still get the same error, I checked Security class
![img1](https://user-images.githubusercontent.com/14570032/59819303-f1bdbb00-932f-11e9-80af-42da1e7e6ec4.png)
and controller responce
![img3](https://user-images.githubusercontent.com/14570032/59819316-000bd700-9330-11e9-94a3-be876796893e.png)
Seems like Security class isn't fully implemented

**Comment by CT-VG** [comment]
What I can see from you screenshots:
You are expecting a de.varengold.cdl.core.model.security.Security object and you get a de.varengold.cdl.core.model.security.bond.Bond object which extends the Security-class.
This should work.

I added the json type info to the Security class (same as creditfacility -> term facility) hopefully this will solve your issues.

Now the result looks like this:
```json
{
    "@class": "de.varengold.cdl.core.model.security.bond.Bond",
    "isin": "XS0802005289",
    "name": "Republic of Bulgaria 4,25 07/09/17",
    "emittendId": 9494,
    "currencyIso": "EUR",
    "exchangeTradedYN": "Y",
    "symbol2": null,
    "type": 2,
    "emission": "2012-07-09",
    "redemption": "2017-07-09",
    "interest": 9,
    "nachrangYN": "N",
    "coverage": 0,
    "guaranteed": 0,
    "perpetualYN": "N"
}
```
